server:
  port: 7004
  error.include-message: always

app:
  eureka-server: localhost
  eureka-username: eureka_client
  eureka-password: CH3FKo(kEY;1g9JEFCG&urODeu24N=Tc
  exchange-api-url: https://currency-conversion-and-exchange-rates.p.rapidapi.com

spring:
  application:
    name: exchange-service

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

resilience4j:
  circuitbreaker:
    instances:
      exchangeApi:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest

  timelimiter:
    instances:
      exchangeApi:
        timeoutDuration: 6s # External API call

  retry:
    instances:
      exchangeApi:
        maxAttempts: 5 # External API call
        waitDuration: 500 # External API call
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest



springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.therealuhlarzoltan.expensables.microservices.exchange
    - hu.therealuhlarzoltan.expensables.api.microservices.core.exchange

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    hu.therealuhlarzoltan: INFO

---
spring.config.activate.on-profile: docker


app:
  eureka-server-1: eureka-server-1
  eureka-server-2: eureka-server-2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-1}:8761/eureka/, http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-2}:8761/eureka/



