server:
  port: 8001
  error.include-message: always

app:
  eureka-server: localhost
  eureka-username: eureka_client
  eureka-password: CH3FKo(kEY;1g9JEFCG&urODeu24N=Tc
  account-service-url: http://account-service
  expense-service-url: http://expense-service
  income-service-url: http://income-service
  exchange-service-url: http://exchange-service
  health-check-path: /actuator/health


spring:
  application:
    name: cashflow-client

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    function.definition: accountResponseProcessor;incomeResponseProcessor;expenseResponseProcessor
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        accounts-out-0:
          destination: accounts
          producer:
            required-groups: auditGroup
        expenses-out-0:
          destination: expenses
          producer:
            required-groups: auditGroup
        incomes-out-0:
          destination: incomes
          producer:
            required-groups: auditGroup
        accountResponseProcessor-in-0:
          destination: accountResponses
          group: accountResponsesGroup
          contentType: application/json
        incomeResponseProcessor-in-0:
          destination: incomeResponses
          group: incomeResponsesGroup
          contentType: application/json
        expenseResponseProcessor-in-0:
          destination: expenseResponses
          group: expenseResponsesGroup
          contentType: application/json

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

resilience4j:
  circuitbreaker:
    instances:
      exchangeService:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.UnprocessableEntity
      incomeService:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
      expenseService:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
      accountService:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10000
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest

  timelimiter:
    instances:
      exchangeService:
        timeoutDuration: 6s # External API call
      incomeService:
        timeoutDuration: 5s
      expenseService:
        timeoutDuration: 5s
      accountService:
        timeoutDuration: 5s

  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
      incomeService:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
      expenseService:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
      exchangeService:
        maxAttempts: 5 # External API call
        waitDuration: 500 # External API call
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
        ignoreExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException.BadRequest
          - org.springframework.web.reactive.function.client.WebClientResponseException.UnprocessableEntity


springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.therealuhlarzoltan.expensables.microservices.cashflow
    - hu.therealuhlarzoltan.expensables.api.microservices.composite.cashflow

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    hu.therealuhlarzoltan: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springdoc: INFO

---
spring.config.activate.on-profile: docker


app:
  eureka-server-1: eureka-server-1
  eureka-server-2: eureka-server-2

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-1}:8761/eureka/, http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-2}:8761/eureka/



