server:
  port: 7100
  error.include-message: always

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:mysql://localhost/auth_db
    username: securityUser
    password: securityPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: Mxvc5F1+FzpPjvRpYz/4ujD+KEDQnCpXxJ0WltbZKQwLRmG8GxDNmttF8HYMe02AOZ00zt2Edo4NsoFF2Ygq7A==
  expiration: 86400000

authentication:
  roles:
    default: ROLE_USER

logging:
  level:
    root: info
    org.springframework.security: trace