server:
  port: 7001
  error.include-message: always

app:
  eureka-server: localhost
  eureka-username: eureka_client
  eureka-password: CH3FKo(kEY;1g9JEFCG&urODeu24N=Tc


spring:
  application:
    name: expense-service

  data.mongodb:
    host: localhost
    port: 27017
    database: expense_record_db
    auto-index-creation: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    messageProcessor-in-0:
      destination: expenses
      group: expensesGroup
    expenseResponses-out-0:
      destination: expenseResponses
      producer:
        requiredGroups: auditGroup
      contentType: application/json

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.messageProcessor-in-0.consumer:
  autoBindDlq: true
  republishToDlq: true

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5


springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/api-docs
  paths-to-match: /**
  packages-to-scan:
    - hu.therealuhlarzoltan.expensables.microservices.expense
    - hu.therealuhlarzoltan.expensables.api.microservices.core.expense

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    hu.therealuhlarzoltan: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springdoc: INFO

---
spring.config.activate.on-profile: docker


app:
  eureka-server-1: eureka-server-1
  eureka-server-2: eureka-server-2


spring.data.mongodb.host: mongodb


eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-1}:8761/eureka/, http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server-2}:8761/eureka/
